# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainLogin):
        MainLogin.setObjectName("MainLogin")
        MainLogin.resize(667, 500)
        MainLogin.setMinimumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, -30, 721, 541))
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(320, 180, 61, 51))
        self.frame.setStyleSheet("\n"
"image: url(:/新前缀/img/buttom/钻石_diamond.svg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_login.setGeometry(QtCore.QRect(310, 400, 70, 30))
        self.pushButton_login.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(220, 310, 70, 50))
        self.label_3.setMinimumSize(QtCore.QSize(70, 50))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(90, 100, 500, 81))
        self.label.setMinimumSize(QtCore.QSize(500, 0))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(310, 270, 150, 25))
        self.lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(220, 260, 70, 50))
        self.label_2.setMinimumSize(QtCore.QSize(70, 50))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 320, 150, 25))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 22))
        self.menubar.setObjectName("menubar")
        MainLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainLogin)
        self.statusbar.setObjectName("statusbar")
        MainLogin.setStatusBar(self.statusbar)

        self.retranslateUi(MainLogin)
        QtCore.QMetaObject.connectSlotsByName(MainLogin)

    def retranslateUi(self, MainLogin):
        _translate = QtCore.QCoreApplication.translate
        MainLogin.setWindowTitle(_translate("MainLogin", "MainWindow"))
        self.pushButton_login.setToolTip(_translate("MainLogin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">登录</span></p></body></html>"))
        self.pushButton_login.setText(_translate("MainLogin", "登录"))
        self.label_3.setText(_translate("MainLogin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">密码：</span></p></body></html>"))
        self.label.setText(_translate("MainLogin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">欢迎使用图像预处理及去模糊平台</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainLogin", "gsy"))
        self.label_2.setText(_translate("MainLogin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">管理员：</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainLogin", "123"))
import resources_rc
